# Generated by Django 3.2 on 2021-05-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=10)),
                ('ingredient', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=10)),
            ],
        ),
    ]
